dist: xenial
language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
install:
    - "pip install -e ."
    - "pip install pytest-cov"
    - "pip install coveralls>=1.1"
script: "pytest --cov pymbtiles --cov-report term-missing"
after_success:
    - coveralls || echo "!! intermittent coveralls failure"
