language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install -e ."
  - "pip install -e .[test]"
  - "pip install coveralls>=1.1"
script: "py.test --cov pymbtiles --cov-report term-missing"
after_success:
  - coveralls || echo "!! intermittent coveralls failure"